# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
variables:
  IMAGE_NAME: "golang"
  IMAGE_VERSION: "1.18.3"
  BUILD_TO: "test"
  APP_IMAGE: "$CI_REGISTRY_IMAGE/gotestapp:$CI_COMMIT_SHORT_SHA"

stages:
  - build
  - image_build
  - run

image: "$IMAGE_NAME:$IMAGE_VERSION"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        BUILD_TO: "main"
    - when: always

build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/go_source
    - go build .
  artifacts:
    paths:
      - go_source/main
    expire_in: 1 week
  tags:
    - main

docker_build:
  stage: image_build
  image: "docker:stable"
  script:
    - mkdir ~/.docker; echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - docker build --tag $APP_IMAGE .
    - docker push $APP_IMAGE
  tags:
    - main

run:
  stage: run
  image: "gitlab.local.com:5050/and/workbox/workbox:latest"
  script:
    - make deploy
  tags:
    - main
