---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: "{{ CI_COMMIT_REF_NAME }}"
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: "{{ APP_IMAGE }}"
      imagePullSecrets:
      - name: regcred