- name: Log into DockerHub
  become: true
  docker_login:
    username: "{{ DOCKERUSER }}"
    password: "{{ DOCKERPASS }}"
    registry_url: gitlab.local.com:5050
    validate_certs: no
    ca_cert: /usr/local/share/ca-certificates/gitlab.crt

- name: Create .kube dir for root
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copy k8s config for root user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: k8s registry secret
  become: true
  command: "kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=/root/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson --namespace {{ CI_COMMIT_REF_NAME }}"
  ignore_errors: true

- name: Create namespace
  become: false
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/namespace.yml') | from_yaml }}"

- name: Deploy application to k8s cluster
  become: false
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/deployment.yml') | from_yaml }}"