- name: Log into DockerHub
  docker_login:
    username: "{{ DOCKERUSER }}"
    password: "{{ DOCKERPASS }}"
    registry_url: gitlab.local.com:5050
    reauthorize: yes

- name: Deploy application to k8s cluster
  become: false
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/deployment.yml') | from_yaml }}"