- name: Log into DockerHub
  docker_login:
    username: "{{ git.DOCKERUSER }}"
    password: "{{ git.DOCKERPASS }}"

- name: Deploy application to k8s cluster
  become: false
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/deployment.yml') | from_yaml }}"